version: "3.8"

services:
  db-test:
    image: postgres:16.1-alpine3.19
    restart: always
    user: postgres
    env_file:
      - .env.test
    volumes:
      - db-test:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      retries: 5
    networks:
      - test
  api-test:
    user: "fastify-build"
    build:
      context: .
      target: test
    env_file:
      - .env.test
    environment:
      NODE_ENV: test
      POSTGRES_HOST: db-test
    depends_on:
      db-test:
        condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    networks:
      - test

volumes:
  db-test:

networks:
  test:
